version: 0.2
phases:
  install:
    commands:
      - echo install steps...
  pre_build:
    commands:
      - echo Check AWS, Git, Python version
      - aws --version && git --version && python --version
      - echo Check ENV Variable
      - printenv
      - cd $CODEBUILD_SRC_DIR
      - pwd
      
      - echo scan credential info with git-secrets
      - git clone https://github.com/awslabs/git-secrets.git
      - cd git-secrets && make install
      - git secrets --register-aws --global
      - ls -la
      - export GIT_DISCOVERY_ACROSS_FILESYSTEM=1
      - cd $CODEBUILD_SRC_DIR && git init
      - git add . 
      - git rm --cached -f git-secrets
      - cd $CODEBUILD_SRC_DIR && git-secrets --scan
      
      - aws s3 cp s3://rll-ssl-key/wildcard.ralali.xyz.crt $CODEBUILD_SRC_DIR
      - aws s3 cp s3://rll-ssl-key/wildcard.ralali.xyz.key $CODEBUILD_SRC_DIR
      - aws s3 cp s3://rll-api-seller-dev/.env $CODEBUILD_SRC_DIR
      - ls -la
      - cat .env
      - echo Logging into AWS ECR...
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
      - REPOSITORY_URI=518667233221.dkr.ecr.ap-southeast-1.amazonaws.com/rll-api-seller-dev
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo build Docker image on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest -f ./docker/Dockerfile-dev .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing Image Definitions File...
      - printf '[{"name":"api-seller","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > api-seller-dev.json
artifacts:
  type: zip
  files:
    - "**/*"
