FROM 518667233221.dkr.ecr.ap-southeast-1.amazonaws.com/dev-project-builder/dev_builder_php_7.2_fpm_alpine:latest

# Getting code into container 
RUN mkdir /var/www/php/
RUN mkdir /var/www/php/apiseller
ADD . /var/www/php/apiseller
WORKDIR /var/www/php/apiseller
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.notused
COPY wildcard.ralali.xyz.crt /etc/nginx/
COPY wildcard.ralali.xyz.key /etc/nginx/
COPY ./docker/nginx.conf /etc/nginx/
COPY ./docker/site-dev.conf /etc/nginx/conf.d/
RUN cd /var/www/php/apiseller

# Install composer
#RUN cd /var/www/php/apiseller
#RUN chmod +x composer-install.sh
#RUN ./composer-install.sh

# Install project PHP depedency
RUN cd /var/www/php/apiseller
RUN composer install
RUN chmod 777 vendor/ -R
RUN chmod 777 storage/ -R 
#RUN vendor/bin/codecept run -c codeception.yml --html

EXPOSE 443

CMD nginx && php-fpm

